import './style.css';
import { initKeygen } from './ui/keygen';
import { initWhip } from './ui/whip';
import { initWhipViz } from './ui/whipviz';
import { initVerify } from './ui/verify';
import { initForge } from './ui/forge';
import { initLedger } from './ui/ledger';
import { initKat } from './ui/kat';
import { initPreconditions } from './ui/preconditions';
import { initPredictions } from './ui/predict';

initKeygen();
initWhipViz();
initWhip();
initVerify();
initForge();
initLedger();
initKat();
initPreconditions();
initPredictions();
